#  .travis.yml 配置信息
# 配置语言
language: node_js
# 语言版本 stable
node_js: stable


# S: Build Lifecycle


# 安装依赖
install:
  - npm install hexo-cli -g
  - npm install -g hexo-generator-search
  - npm install

 # 部署命令
script:
  - hexo -v
  - hexo clean
  - hexo g

# 提交内容及git 用户信息
 after_script:
  - cd ./public
# - git init
  - git config user.name "imtianx"
  - git config user.email "2360633699@qq.com"
  - git add .
  - git commit -m "Update blog"
  - git push --force --quiet "https://${GITHUB_BLOG_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

# 项目所在分支
branches:
  only:
    - blog-resources

# 缓存，加速构建
cache:
  directories:
    - "node_modules"


# 项目git地址	
env:
 global:
   - GH_REF: github.com/imtianx/imtianx.github.io.git
