#  .travis.yml 配置信息
# 配置语言
language: node_js
# 语言版本 stable
node_js: stable

# 缓存，加速构建
cache:
  directories:
    - node_modules

# 项目所在分支
branches:
  only:
    - theme_matery

# 安装依赖
before_install:
  - npm i hexo --S
  - npm i hexo-prism-plugin -S
  - npm i hexo-permalink-pinyin -S
  - npm i hexo-wordcount -S
  - npm i hexo-generator-feed -S
  - npm i hexo-generator-search -S
  - npm i hexo-filter-github-emojis -S
  - npm i


before_script:
- git config --global user.name 'imtianx'
- git config --global user.email 'imtianx@gmail.com'
- sed -i'' "s~git@github.com:imtianx/imtianx.github.io.git~https://${GITHUB_BLOG_TOKEN}@${GH_REF}~" _config.yml


script:
  - hexo generate


deploy:
  skip_cleanup: true
  provider: script
  script: sh deploy.sh
  on:
    branch: theme_matery

# 项目git地址	
env:
 global:
   - GH_REF: github.com/imtianx/imtianx.github.io.git


